CREATE TABLE IF NOT EXISTS `lucky5_market_route_item` (
  `id` varchar(64) NOT NULL,
  `user_id` bigint NOT NULL,
  `order_id` varchar(64) NOT NULL,
  `bet_item_id` varchar(64) NOT NULL,
  `period` varchar(40) NOT NULL,
  `play` varchar(100) NOT NULL,
  `selection` varchar(100) NOT NULL,
  `route_type` varchar(30) NOT NULL,
  `local_amount` decimal(18,2) NOT NULL DEFAULT 0,
  `market_amount` decimal(18,2) NOT NULL DEFAULT 0,
  `odds` decimal(12,4) NOT NULL DEFAULT 0,
  `local_payout` decimal(18,2) NOT NULL DEFAULT 0,
  `market_guid` varchar(64) NOT NULL,
  `market_bet_id` varchar(100) NOT NULL DEFAULT '',
  `market_serial_no` varchar(100) NOT NULL DEFAULT '',
  `market_bet_count` int NOT NULL DEFAULT 0,
  `market_odds` decimal(12,4) NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'PENDING',
  `attempts` int NOT NULL DEFAULT 0,
  `last_error` varchar(1000) NOT NULL DEFAULT '',
  `next_retry_at` datetime NULL,
  `submitted_at` datetime NULL,
  `confirmed_at` datetime NULL,
  `settled_at` datetime NULL,
  `cancelled_at` datetime NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_lucky5_market_route_bet` (`tenant_id`,`user_id`,`order_id`,`bet_item_id`),
  KEY `idx_lucky5_market_route_guid` (`tenant_id`,`user_id`,`market_guid`),
  KEY `idx_lucky5_market_route_dispatch` (`tenant_id`,`user_id`,`status`,`next_retry_at`),
  KEY `idx_lucky5_market_route_period` (`tenant_id`,`user_id`,`period`,`play`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lucky5 real market routing state';
